/*
 * This file is generated by jOOQ.
 */
package rs.elfak.caprovider.db.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import rs.elfak.caprovider.db.enums.RequestStatus;
import rs.elfak.caprovider.db.enums.RequestType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICertificateRequest extends Serializable {

    /**
     * Setter for <code>certificate_request.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>certificate_request.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>certificate_request.country</code>.
     */
    public void setCountry(String value);

    /**
     * Getter for <code>certificate_request.country</code>.
     */
    public String getCountry();

    /**
     * Setter for <code>certificate_request.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>certificate_request.state</code>.
     */
    public String getState();

    /**
     * Setter for <code>certificate_request.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>certificate_request.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>certificate_request.organization</code>.
     */
    public void setOrganization(String value);

    /**
     * Getter for <code>certificate_request.organization</code>.
     */
    public String getOrganization();

    /**
     * Setter for <code>certificate_request.email</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>certificate_request.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>certificate_request.request_type</code>.
     */
    public void setRequestType(RequestType value);

    /**
     * Getter for <code>certificate_request.request_type</code>.
     */
    public RequestType getRequestType();

    /**
     * Setter for <code>certificate_request.timestamp</code>.
     */
    public void setTimestamp(LocalDateTime value);

    /**
     * Getter for <code>certificate_request.timestamp</code>.
     */
    public LocalDateTime getTimestamp();

    /**
     * Setter for <code>certificate_request.status</code>.
     */
    public void setStatus(RequestStatus value);

    /**
     * Getter for <code>certificate_request.status</code>.
     */
    public RequestStatus getStatus();

    /**
     * Setter for <code>certificate_request.certificate</code>.
     */
    public void setCertificate(Integer value);

    /**
     * Getter for <code>certificate_request.certificate</code>.
     */
    public Integer getCertificate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ICertificateRequest
     */
    public void from(ICertificateRequest from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ICertificateRequest
     */
    public <E extends ICertificateRequest> E into(E into);
}
