/*
 * This file is generated by jOOQ.
 */
package rs.elfak.caprovider.db;


import rs.elfak.caprovider.db.tables.Certificate;
import rs.elfak.caprovider.db.tables.CertificateRequest;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>certificate</code>.
     */
    public static final Certificate CERTIFICATE = Certificate.CERTIFICATE;

    /**
     * The table <code>certificate_request</code>.
     */
    public static final CertificateRequest CERTIFICATE_REQUEST = CertificateRequest.CERTIFICATE_REQUEST;
}
