/*
 * This file is generated by jOOQ.
 */
package rs.elfak.ocspresponder.db.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import rs.elfak.ocspresponder.db.DefaultSchema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum RequestType implements EnumType {

    EMAIL_CERT("EMAIL_CERT"),

    INTERMEDIATE_CA("INTERMEDIATE_CA");

    private final String literal;

    private RequestType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public String getName() {
        return "request_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static RequestType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(RequestType.class, literal);
    }
}
