/*
 * This file is generated by jOOQ.
 */
package rs.elfak.ocspresponder.db.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import rs.elfak.ocspresponder.db.DefaultSchema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum SubjectType implements EnumType {

    END_ENTITY("END_ENTITY"),

    INTERMEDIATE_CA("INTERMEDIATE_CA"),

    ROOT_CA("ROOT_CA");

    private final String literal;

    private SubjectType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public String getName() {
        return "subject_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static SubjectType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(SubjectType.class, literal);
    }
}
